baseURL = "https://lyhxavier.github.io/Psychology/"
defaultContentLanguage = "en"
languageCode = "en-us"
title = "xavierlyh's Academic Archive"

theme = "uBlogger"

[params]
	# uBlogger theme version
	version = "2.0.X"
	defaultTheme = "dark"
	description = "An Academic Psychology Blog"
	keywords = ["Academic", "Psychology"]

	[params.home]
    rss = 10
    	[params.home.profile]
    	# Cover page introduction to myself
    		enable = true
    		avatarURL = "images/avatar.jpg"
    		title = "xavierlyh | Academic Psychology Blog"
        subtitle = "An academic archive of my psychological writings"
        social = true

  [params.social]
    Linkedin = "xavierlyh"
    Instagram = "xavierlyh_"
    Reddit = "Claxui"
    Email = "xavierlimyanheng@gmail.com"

  [params.page]
    hiddenFromHomePage = false
    hiddenFromSearch = false
    twemoji = false
    ruby = true
    fraction = true
    fontawesome = true
    linkToMarkdown = true
    rssFullText = false

    [params.page.share]
      enable = true
      Facebook = true
      Twitter = true
      Linkedin = true

  [params.search]
    enable = true
    type = "lunr"
    contentLength = 4000
    maxResultLength = 10
    snippetLength = 30
    highlightTag = "em"
    absoluteURL = false

  [params.section]
    paginate = 20
    dateFormat = "01-02"
    rss = 10

  [params.list]
    paginate = 20
    dateFormat = "01-02"
    rss = 10

  [params.header]
    desktopMode = "fixed"
    mobileMode = "auto"

  [params.footer]
    enable = true
    custom = ''
    hugo = true
    copyright = true
    author = true
    since = 2021
    license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

[menu]
	[[menu.main]]
	 # Storage of all relevant posts
	 identifier = "posts"
	 name = "Posts"
	 url = "posts/"
	 weight = 1

	[[menu.main]]
	 # Categories refer to field of psychology the writing represents
    identifier = "categories"
   	name = "Categories"
    url = "categories/"
    weight = 2

  [[menu.main]]
    # Tags refer to important themes of the writing
    identifier = "tags"
    name = "Tags"
    url = "tags/"
    weight = 3

  [[menu.main]]
    # About refer to a description of myself
    identifier = "about"
    name = "About"
    url = "about/"
    weight = 4

[outputs]
  home = ["HTML", "RSS", "JSON"]

[Permalinks]
  posts = ":filename"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      unsafe = true